---
- name: Install stuff and configure
  hosts: all
  become: no

  tasks:
    - name: Create tmp directory
      ansible.builtin.file:
        path: /tmp/dotfiles
        state: directory

    - name: Download nvim
      ansible.builtin.get_url:
        url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
        dest: /tmp/dotfiles/nvim-linux64.tar.gz
